### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#2]
We need to come up with something to be able to debug the programs.

Suggested by @IngvarJackal
### Pieces
- [ ] #50 Introduce debug mode
- [ ] #52 Trigger debug mode by a mark before term
- [ ] #53 Trigger debug mode by ^C

**Comment by Minoru** [comment]
A pen, a notebook and a set of big, powerful brains should do the trick.

**Comment by rexim** [comment]
@Minoru don't forget a big cup of tea!!

**Comment by Minoru** [comment]
Oh, right! _Now_ I understand why implementing debug in Horta would be such a hard engineering problem.

**Comment by rexim** [comment]
There is an idea to implement that in a form of a trace or something

**Comment by rexim** [comment]
After finishing with #35 I think it will be quite easy to implement step based tracing or something like that.
