### ISSUE TITLE
Use classpath modules in REPL autocompletion

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#257]
Split from https://github.com/morganey-lang/Morganey/issues/222#issuecomment-252682563

**Comment by rexim** [comment]
This issue has been split.

### Pieces

- [x] #303 Develop morganey module index format
- [x] #305 Make ModuleFinder collect and merge indices
- [x] #306 Use indices mechanism in ReplAutocompletion
- [x] #304 Make stdlib subproject build morganey module index
