### ISSUE TITLE
Refactor me.rexim.morganey.util._ package

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#266]
[package.scala](https://github.com/morganey-lang/Morganey/blob/4d258629c75581a19a1ef5c951bf7e606a8fad71/kernel/src/main/scala/me/rexim/morganey/util/package.scala)
### Pieces
- [x] Move `sequence` stuff to `me.rexim.morganey.monad`
- [x] Move `unquoteString` to `LambdaParser`
- [x] #276 Move `validRegex` to `Commands`
- [x] #277 Move `reader` stuff to `me.rexim.morganey.reader`
- [x] #278 Move `ParseOps` and `InputSource` closer to `LambdaParser`
- [x] #279 Move logic inside of `ParseOps.parseWith` to `InputSource`
