### ISSUE TITLE
Prelude mechanism

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#79]
Derived from #73 

A module in the `std` folder that is always automatically loaded in any Morganey session

### Pieces

- [x] #348 Implement prelude mechanism for execution mode
- [x] #351 Use prelude module injection mechanism for REPL mode
- [x] #346 Update samples with respect to autoloading of std.prelude module
